// Дані пошуку для Fuse.js - Українська
// Поєднує сторінки застосунку та посилання на документацію

import type { SearchItem } from "./searchData.en";

export const searchData: SearchItem[] = [
    // ===== СТОРІНКИ ЗАСТОСУНКУ =====
    {
        title: "Алгоритми",
        path: "/algorithms",
        content: "Перегляд активних торгових алгоритмів та їхніх поточних сигналів. Моніторинг сигналів купівлі та продажу для Bitcoin та Binance Coin.",
        keywords: ["алгоритми", "сигнали", "торгівля", "btc", "bnb", "купівля", "продаж"],
    },
    {
        title: "Екземпляри",
        path: "/instances",
        content: "Керуйте екземплярами автоматичних торгових ботів. Створюйте, редагуйте, призупиняйте або видаляйте торгових ботів.",
        keywords: ["екземпляри", "боти", "торгівля", "автоматичний", "керування"],
    },
    {
        title: "Сповіщення",
        path: "/notifications",
        content: "Налаштуйте сповіщення про торгові сигнали через Telegram. Налаштуйте оповіщення для конкретних інструментів та стратегій.",
        keywords: ["сповіщення", "оповіщення", "telegram", "сигнали"],
    },
    {
        title: "Бек-тест",
        path: "/backtest",
        content: "Дослідіть історичну ефективність торгових стратегій. Перегляд історії угод з різними рівнями кредитного плеча.",
        keywords: ["бек-тест", "історія", "ефективність", "плече", "тестування"],
    },
    {
        title: "План",
        path: "/plan",
        content: "Керуйте планом підписки. Перегляд деталей виставлення рахунків та оновлення підписки.",
        keywords: ["план", "підписка", "рахунки", "ціни", "оплата"],
    },

    // ===== ДОКУМЕНТАЦІЯ (Зовнішні посилання) =====
    {
        title: "Головна документації",
        path: "https://docs.monkeys.finance/uk",
        section: "Документація",
        content: "Ласкаво просимо до документації Monkeys Finance. Дізнайтеся, як використовувати нашу платформу алгоритмічної торгівлі.",
        keywords: ["головна", "ласкаво просимо", "документація", "docs", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "Про нас",
        path: "https://docs.monkeys.finance/uk/about",
        section: "Документація",
        content: "Про Monkeys Finance та нашу місію надавати рішення для алгоритмічної торгівлі.",
        keywords: ["про нас", "місія", "компанія", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "Посібник з екземплярів",
        path: "https://docs.monkeys.finance/uk/instances",
        section: "Документація",
        content: "Що таке екземпляр? Екземпляр — це конфігурація автоматичного торгового бота, що представляє ваші особисті торгові уподобання.",
        keywords: ["екземпляр", "бот", "торгівля", "автоматичний", "конфігурація", "посібник"],
        isExternal: true,
    },
    {
        title: "Створення екземпляра",
        path: "https://docs.monkeys.finance/uk/instances#creating-instance",
        section: "Документація",
        content: "Щоб створити новий екземпляр, відкрийте сторінку Екземпляри в панелі керування Monkeys Finance, натисніть Додати екземпляр.",
        keywords: ["створити", "додати", "новий", "екземпляр", "налаштування"],
        isExternal: true,
    },
    {
        title: "Чому USDC?",
        path: "https://docs.monkeys.finance/uk/instances#why-usdc",
        section: "Документація",
        content: "Усі торгові пари використовують USDC як базову валюту замість USDT. Це забезпечує відповідність регуляціям MiCA ЄС.",
        keywords: ["usdc", "стейблкоїн", "mica", "регуляція", "європа", "відповідність"],
        isExternal: true,
    },
    {
        title: "Режим Testnet",
        path: "https://docs.monkeys.finance/uk/instances#testnet-mode",
        section: "Документація",
        content: "Режим testnet дозволяє тестувати торгові стратегії з демо-коштами перед ризиком реальних грошей.",
        keywords: ["testnet", "демо", "тест", "паперова торгівля", "симуляція"],
        isExternal: true,
    },
    {
        title: "Посібник зі сповіщень",
        path: "https://docs.monkeys.finance/uk/notifications",
        section: "Документація",
        content: "Сповіщення інформують вас про торгові сигнали в реальному часі. Налаштуйте, які сигнали ви хочете отримувати.",
        keywords: ["сповіщення", "оповіщення", "сигнали", "telegram", "реальний час", "посібник"],
        isExternal: true,
    },
    {
        title: "Налаштування Telegram",
        path: "https://docs.monkeys.finance/uk/notifications#telegram",
        section: "Документація",
        content: "Отримуйте миттєві сповіщення про торгові сигнали через Telegram. Знайдіть @algo_squid_bot та надішліть команду /start.",
        keywords: ["telegram", "бот", "налаштування", "месенджер", "чат"],
        isExternal: true,
    },
    {
        title: "Алгоритми та інструменти",
        path: "https://docs.monkeys.finance/uk/instruments",
        section: "Документація",
        content: "Дізнайтеся про наші алгоритми та чому ми фокусуємося на Bitcoin та Binance Coin для наших торгових стратегій.",
        keywords: ["алгоритми", "інструменти", "btc", "bnb", "bitcoin", "binance coin", "посібник"],
        isExternal: true,
    },
    {
        title: "Bitcoin (BTC)",
        path: "https://docs.monkeys.finance/uk/instruments#bitcoin",
        section: "Документація",
        content: "Bitcoin залишається беззаперечним лідером крипторинку, займаючи близько 60% загальної ринкової капіталізації.",
        keywords: ["bitcoin", "btc", "крипто", "домінування", "цифрове золото"],
        isExternal: true,
    },
    {
        title: "Binance Coin (BNB)",
        path: "https://docs.monkeys.finance/uk/instruments#binance-coin",
        section: "Документація",
        content: "BNB функціонує як акція в екосистемі Binance. Знижки на торгові комісії, винагороди за стейкінг.",
        keywords: ["bnb", "binance", "coin", "утиліта", "біржа", "стейкінг"],
        isExternal: true,
    },
    {
        title: "Безпека",
        path: "https://docs.monkeys.finance/uk/safety",
        section: "Документація",
        content: "Дізнайтеся, як ми захищаємо ваші дані та забезпечуємо безпеку. Архітектура глибокого захисту.",
        keywords: ["безпека", "захист", "дані", "шифрування"],
        isExternal: true,
    },
    {
        title: "Шифрування API-ключів",
        path: "https://docs.monkeys.finance/uk/safety#api-encryption",
        section: "Документація",
        content: "Багаторівневе шифрування для API-ключів. Шифрування на стороні клієнта, AES-256-GCM, унікальні ключі для кожного користувача.",
        keywords: ["api", "ключі", "шифрування", "aes", "безпечний", "облікові дані"],
        isExternal: true,
    },
    {
        title: "Посібник з бек-тестування",
        path: "https://docs.monkeys.finance/uk/backtest",
        section: "Документація",
        content: "Функція бек-тестування дозволяє дослідити, як наші алгоритми працювали б на реальних історичних даних.",
        keywords: ["бек-тест", "історичний", "ефективність", "симуляція", "тестування", "посібник"],
        isExternal: true,
    },
    {
        title: "Історія угод",
        path: "https://docs.monkeys.finance/uk/backtest#trade-history",
        section: "Документація",
        content: "Детальна таблиця кожної угоди за період бек-тесту. Тип позиції, дати відкриття та закриття, прибуток або збиток.",
        keywords: ["угода", "історія", "таблиця", "прибуток", "збиток", "комісії"],
        isExternal: true,
    },
    {
        title: "Посібник з оплати",
        path: "https://docs.monkeys.finance/uk/payments",
        section: "Документація",
        content: "Дізнайтеся про плани підписки, виставлення рахунків та варіанти оплати в Monkeys Finance.",
        keywords: ["оплата", "підписка", "рахунки", "ціни", "плани", "посібник"],
        isExternal: true,
    },
    {
        title: "Плани підписки",
        path: "https://docs.monkeys.finance/uk/payments#subscription-plans",
        section: "Документація",
        content: "Місячний план зі щомісячною оплатою або річний план з оплатою раз на рік з економією 20%. Повний доступ до всіх функцій.",
        keywords: ["підписка", "місячний", "річний", "плани", "ціни"],
        isExternal: true,
    },
    {
        title: "Безкоштовний пробний період",
        path: "https://docs.monkeys.finance/uk/payments#free-trial",
        section: "Документація",
        content: "Нові користувачі починають з безкоштовного пробного періоду для вивчення всіх функцій. Платіжна інформація не потрібна.",
        keywords: ["безкоштовно", "пробний", "без оплати", "вивчити", "нові користувачі"],
        isExternal: true,
    },
    {
        title: "Машинне навчання",
        path: "https://docs.monkeys.finance/uk/ml",
        section: "Документація",
        content: "Дізнайтеся, як наша платформа використовує машинне навчання для покращення торгових рішень та фільтрації сигналів.",
        keywords: ["машинне навчання", "ml", "шї", "фільтр", "сигнали"],
        isExternal: true,
    },
    {
        title: "Підтримка",
        path: "https://docs.monkeys.finance/uk/support",
        section: "Документація",
        content: "Якщо у вас є питання, потрібна допомога або хочете залишити відгук, напишіть нам на monkeys.finance.ca@gmail.com.",
        keywords: ["підтримка", "допомога", "контакт", "email", "питання", "відгук"],
        isExternal: true,
    },
];
