// Datos de búsqueda para Fuse.js - Español
// Combina páginas de la aplicación y enlaces de documentación

import type { SearchItem } from "./searchData.en";

export const searchData: SearchItem[] = [
    // ===== PÁGINAS DE LA APLICACIÓN =====
    {
        title: "Algoritmos",
        path: "/algorithms",
        content: "Ver algoritmos de trading activos y sus señales actuales. Monitorear señales de compra y venta para Bitcoin y Binance Coin.",
        keywords: ["algoritmos", "señales", "trading", "btc", "bnb", "compra", "venta"],
    },
    {
        title: "Instancias",
        path: "/instances",
        content: "Administra tus instancias de bots de trading automatizado. Crear, editar, pausar o eliminar bots de trading.",
        keywords: ["instancias", "bots", "trading", "automatizado", "administrar"],
    },
    {
        title: "Notificaciones",
        path: "/notifications",
        content: "Configura notificaciones de señales de trading a través de Telegram. Configura alertas para instrumentos y estrategias específicas.",
        keywords: ["notificaciones", "alertas", "telegram", "señales"],
    },
    {
        title: "Backtest",
        path: "/backtest",
        content: "Explora el rendimiento histórico de las estrategias de trading. Ver historial de operaciones con diferentes niveles de apalancamiento.",
        keywords: ["backtest", "historial", "rendimiento", "apalancamiento", "pruebas"],
    },
    {
        title: "Plan",
        path: "/plan",
        content: "Administra tu plan de suscripción. Ver detalles de facturación y actualizar o degradar tu suscripción.",
        keywords: ["plan", "suscripción", "facturación", "precios", "pago"],
    },

    // ===== DOCUMENTACIÓN (Enlaces Externos) =====
    {
        title: "Inicio de Documentación",
        path: "https://docs.monkeys.finance/es",
        section: "Documentación",
        content: "Bienvenido a la documentación de Monkeys Finance. Aprende a usar nuestra plataforma de trading algorítmico.",
        keywords: ["inicio", "bienvenido", "documentación", "docs", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "Acerca de",
        path: "https://docs.monkeys.finance/es/about",
        section: "Documentación",
        content: "Acerca de Monkeys Finance y nuestra misión de proporcionar soluciones de trading algorítmico.",
        keywords: ["acerca", "misión", "empresa", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "Guía de Instancias",
        path: "https://docs.monkeys.finance/es/instances",
        section: "Documentación",
        content: "¿Qué es una Instancia? Una instancia es una configuración de bot de trading automatizado que representa tus preferencias personales de trading.",
        keywords: ["instancia", "bot", "trading", "automatizado", "configuración", "guía"],
        isExternal: true,
    },
    {
        title: "Crear una Instancia",
        path: "https://docs.monkeys.finance/es/instances#creating-instance",
        section: "Documentación",
        content: "Para crear una nueva instancia, abre la página de Instancias en el dashboard de Monkeys Finance, haz clic en Agregar Instancia.",
        keywords: ["crear", "agregar", "nueva", "instancia", "configuración"],
        isExternal: true,
    },
    {
        title: "¿Por qué USDC?",
        path: "https://docs.monkeys.finance/es/instances#why-usdc",
        section: "Documentación",
        content: "Todos los pares de trading usan USDC como moneda base en lugar de USDT. Esto asegura cumplimiento con regulaciones MiCA de la UE.",
        keywords: ["usdc", "stablecoin", "mica", "regulación", "europa", "cumplimiento"],
        isExternal: true,
    },
    {
        title: "Modo Testnet",
        path: "https://docs.monkeys.finance/es/instances#testnet-mode",
        section: "Documentación",
        content: "El modo testnet te permite probar tus estrategias de trading con fondos demo antes de arriesgar dinero real.",
        keywords: ["testnet", "demo", "prueba", "paper trading", "simulación"],
        isExternal: true,
    },
    {
        title: "Guía de Notificaciones",
        path: "https://docs.monkeys.finance/es/notifications",
        section: "Documentación",
        content: "Las notificaciones te mantienen informado sobre señales de trading en tiempo real. Configura qué señales quieres recibir.",
        keywords: ["notificaciones", "alertas", "señales", "telegram", "tiempo real", "guía"],
        isExternal: true,
    },
    {
        title: "Configuración de Telegram",
        path: "https://docs.monkeys.finance/es/notifications#telegram",
        section: "Documentación",
        content: "Recibe notificaciones instantáneas de señales de trading vía Telegram. Busca @algo_squid_bot y envía el comando /start.",
        keywords: ["telegram", "bot", "configuración", "mensajería", "chat"],
        isExternal: true,
    },
    {
        title: "Algoritmos e Instrumentos",
        path: "https://docs.monkeys.finance/es/instruments",
        section: "Documentación",
        content: "Aprende sobre nuestros algoritmos y por qué nos enfocamos en Bitcoin y Binance Coin para nuestras estrategias de trading.",
        keywords: ["algoritmos", "instrumentos", "btc", "bnb", "bitcoin", "binance coin", "guía"],
        isExternal: true,
    },
    {
        title: "Bitcoin (BTC)",
        path: "https://docs.monkeys.finance/es/instruments#bitcoin",
        section: "Documentación",
        content: "Bitcoin sigue siendo el líder indiscutible en el mercado cripto, con aproximadamente el 60% de la capitalización total del mercado.",
        keywords: ["bitcoin", "btc", "cripto", "dominancia", "oro digital"],
        isExternal: true,
    },
    {
        title: "Binance Coin (BNB)",
        path: "https://docs.monkeys.finance/es/instruments#binance-coin",
        section: "Documentación",
        content: "BNB funciona como una acción en el ecosistema de Binance. Tarifas de trading con descuento, recompensas de staking.",
        keywords: ["bnb", "binance", "coin", "utilidad", "exchange", "staking"],
        isExternal: true,
    },
    {
        title: "Seguridad",
        path: "https://docs.monkeys.finance/es/safety",
        section: "Documentación",
        content: "Aprende cómo protegemos tus datos y garantizamos la seguridad. Arquitectura de defensa en profundidad.",
        keywords: ["seguridad", "protección", "datos", "encriptación"],
        isExternal: true,
    },
    {
        title: "Encriptación de Claves API",
        path: "https://docs.monkeys.finance/es/safety#api-encryption",
        section: "Documentación",
        content: "Encriptación multicapa para claves API. Encriptación del lado del cliente, AES-256-GCM, claves únicas por usuario.",
        keywords: ["api", "claves", "encriptación", "aes", "seguro", "credenciales"],
        isExternal: true,
    },
    {
        title: "Guía de Backtesting",
        path: "https://docs.monkeys.finance/es/backtest",
        section: "Documentación",
        content: "Nuestra función de backtesting te permite explorar cómo habrían funcionado nuestros algoritmos con datos históricos reales.",
        keywords: ["backtest", "histórico", "rendimiento", "simulación", "pruebas", "guía"],
        isExternal: true,
    },
    {
        title: "Historial de Operaciones",
        path: "https://docs.monkeys.finance/es/backtest#trade-history",
        section: "Documentación",
        content: "Tabla detallada de cada operación durante el período de backtest. Tipo de posición, fechas de apertura y cierre, ganancia o pérdida.",
        keywords: ["operación", "historial", "tabla", "ganancia", "pérdida", "comisiones"],
        isExternal: true,
    },
    {
        title: "Guía de Pagos",
        path: "https://docs.monkeys.finance/es/payments",
        section: "Documentación",
        content: "Conoce los planes de suscripción, facturación y opciones de pago en Monkeys Finance.",
        keywords: ["pagos", "suscripción", "facturación", "precios", "planes", "guía"],
        isExternal: true,
    },
    {
        title: "Planes de Suscripción",
        path: "https://docs.monkeys.finance/es/payments#subscription-plans",
        section: "Documentación",
        content: "Plan mensual facturado cada mes, o plan anual facturado una vez al año con 20% de ahorro. Acceso completo a todas las funciones.",
        keywords: ["suscripción", "mensual", "anual", "planes", "precios"],
        isExternal: true,
    },
    {
        title: "Prueba Gratuita",
        path: "https://docs.monkeys.finance/es/payments#free-trial",
        section: "Documentación",
        content: "Los nuevos usuarios comienzan con una prueba gratuita para explorar todas las funciones. No se requiere información de pago.",
        keywords: ["gratis", "prueba", "sin pago", "explorar", "nuevos usuarios"],
        isExternal: true,
    },
    {
        title: "Machine Learning",
        path: "https://docs.monkeys.finance/es/ml",
        section: "Documentación",
        content: "Aprende cómo nuestra plataforma usa machine learning para mejorar las decisiones de trading y filtrar señales.",
        keywords: ["machine learning", "ml", "ia", "filtro", "señales"],
        isExternal: true,
    },
    {
        title: "Soporte",
        path: "https://docs.monkeys.finance/es/support",
        section: "Documentación",
        content: "Si tienes preguntas, necesitas ayuda o quieres dar feedback, envíanos un email a monkeys.finance@gmail.com.",
        keywords: ["soporte", "ayuda", "contacto", "email", "preguntas", "feedback"],
        isExternal: true,
    },
];
