// Search data containing all content for Fuse.js search
// Combines app pages and documentation links

export interface SearchItem {
    title: string;
    path: string;
    section?: string;
    content: string;
    keywords: string[];
    isExternal?: boolean; // true for docs links
}

export const searchData: SearchItem[] = [
    // ===== APP PAGES =====
    {
        title: "Algorithms",
        path: "/algorithms",
        content: "View active trading algorithms and their current signals. Monitor buy and sell signals for Bitcoin and Binance Coin.",
        keywords: ["algorithms", "signals", "trading", "btc", "bnb", "buy", "sell"],
    },
    {
        title: "Instances",
        path: "/instances",
        content: "Manage your automated trading bot instances. Create, edit, pause, or delete trading bots.",
        keywords: ["instances", "bots", "trading", "automated", "manage"],
    },
    {
        title: "Notifications",
        path: "/notifications",
        content: "Configure trading signal notifications via Telegram. Set up alerts for specific instruments and strategies.",
        keywords: ["notifications", "alerts", "telegram", "signals"],
    },
    {
        title: "Backtest",
        path: "/backtest",
        content: "Explore historical performance of trading strategies. View trade history with different leverage levels.",
        keywords: ["backtest", "history", "performance", "leverage", "testing"],
    },
    {
        title: "Plan",
        path: "/plan",
        content: "Manage your subscription plan. View billing details and upgrade or downgrade your subscription.",
        keywords: ["plan", "subscription", "billing", "pricing", "payment"],
    },

    // ===== DOCUMENTATION (External Links) =====
    {
        title: "Documentation Home",
        path: "https://docs.monkeys.finance/en",
        section: "Documentation",
        content: "Welcome to Monkeys Finance documentation. Learn how to use our algorithmic trading platform.",
        keywords: ["home", "welcome", "documentation", "docs", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "About",
        path: "https://docs.monkeys.finance/en/about",
        section: "Documentation",
        content: "About Monkeys Finance and our mission to provide algorithmic trading solutions.",
        keywords: ["about", "mission", "company", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "Instances Guide",
        path: "https://docs.monkeys.finance/en/instances",
        section: "Documentation",
        content: "What is an Instance? An instance is an automated trading bot configuration that represents your personal trading preferences. Once created, instances are stored in the cloud and run 24/7.",
        keywords: ["instance", "bot", "trading", "automated", "configuration", "guide"],
        isExternal: true,
    },
    {
        title: "Creating an Instance",
        path: "https://docs.monkeys.finance/en/instances#creating-instance",
        section: "Documentation",
        content: "To create a new instance, open the Instances page in the Monkeys Finance dashboard, click Add Instance, and fill in the instance details.",
        keywords: ["create", "add", "new", "instance", "setup"],
        isExternal: true,
    },
    {
        title: "Position Size Compounding",
        path: "https://docs.monkeys.finance/en/instances#position-compounding",
        section: "Documentation",
        content: "Your position size automatically adjusts based on trading performance, allowing profitable strategies to grow your trading capital over time.",
        keywords: ["position", "size", "compounding", "profit", "capital", "growth"],
        isExternal: true,
    },
    {
        title: "Why USDC?",
        path: "https://docs.monkeys.finance/en/instances#why-usdc",
        section: "Documentation",
        content: "All trading pairs use USDC (USD Coin) as the quote currency instead of USDT. This ensures compliance with EU MiCA regulations.",
        keywords: ["usdc", "stablecoin", "mica", "regulation", "europe", "compliance"],
        isExternal: true,
    },
    {
        title: "Testnet Mode",
        path: "https://docs.monkeys.finance/en/instances#testnet-mode",
        section: "Documentation",
        content: "Testnet mode allows you to test your trading strategies with demo funds before risking real money.",
        keywords: ["testnet", "demo", "test", "paper trading", "simulation"],
        isExternal: true,
    },
    {
        title: "Notifications Guide",
        path: "https://docs.monkeys.finance/en/notifications",
        section: "Documentation",
        content: "Notifications keep you informed about trading signals in real-time. Configure which signals you want to receive.",
        keywords: ["notifications", "alerts", "signals", "telegram", "real-time", "guide"],
        isExternal: true,
    },
    {
        title: "Telegram Setup",
        path: "https://docs.monkeys.finance/en/notifications#telegram",
        section: "Documentation",
        content: "Receive instant trading signal notifications via Telegram. Search for @algo_squid_bot and send /start command.",
        keywords: ["telegram", "bot", "setup", "messaging", "chat"],
        isExternal: true,
    },
    {
        title: "ML Filter Alerts",
        path: "https://docs.monkeys.finance/en/notifications#ml-filter-alerts",
        section: "Documentation",
        content: "When a signal is filtered out by the ML model, you receive a special ML Filter Alert notification.",
        keywords: ["ml", "filter", "machine learning", "alert", "filtered"],
        isExternal: true,
    },
    {
        title: "Algorithms & Instruments",
        path: "https://docs.monkeys.finance/en/instruments",
        section: "Documentation",
        content: "Learn about our algorithms and why we focus on Bitcoin and Binance Coin for our algorithmic trading strategies.",
        keywords: ["algorithms", "instruments", "btc", "bnb", "bitcoin", "binance coin", "guide"],
        isExternal: true,
    },
    {
        title: "How Do Our Algorithms Work?",
        path: "https://docs.monkeys.finance/en/instruments#how-algorithms-work",
        section: "Documentation",
        content: "We won't reveal every detail or secret sauce behind our algorithms, but we share the core principles that drive them.",
        keywords: ["algorithms", "how", "work", "principles", "strategy"],
        isExternal: true,
    },
    {
        title: "Bitcoin (BTC)",
        path: "https://docs.monkeys.finance/en/instruments#bitcoin",
        section: "Documentation",
        content: "Bitcoin remains the undisputed leader in the crypto market, holding around 60% of the total market capitalization. Strategic Bitcoin Reserve.",
        keywords: ["bitcoin", "btc", "crypto", "dominance", "digital gold"],
        isExternal: true,
    },
    {
        title: "Binance Coin (BNB)",
        path: "https://docs.monkeys.finance/en/instruments#binance-coin",
        section: "Documentation",
        content: "BNB functions like a stock in the Binance ecosystem. Discounted trading fees, staking rewards, gas on BNB Chain, token burns.",
        keywords: ["bnb", "binance", "coin", "utility", "exchange", "staking"],
        isExternal: true,
    },
    {
        title: "Safety & Security",
        path: "https://docs.monkeys.finance/en/safety",
        section: "Documentation",
        content: "Learn how we protect your data and ensure security. Defense-in-depth architecture using industry-leading third-party services.",
        keywords: ["safety", "security", "protection", "data", "encryption"],
        isExternal: true,
    },
    {
        title: "API Key Encryption",
        path: "https://docs.monkeys.finance/en/safety#api-encryption",
        section: "Documentation",
        content: "Multi-layer encryption for API keys. Client-side encryption, AES-256-GCM, unique encryption keys per user, AWS Secrets Manager.",
        keywords: ["api", "keys", "encryption", "aes", "secure", "credentials"],
        isExternal: true,
    },
    {
        title: "Payment Security",
        path: "https://docs.monkeys.finance/en/safety#stripe-payments",
        section: "Documentation",
        content: "We use Stripe as our payment processor. We never see or store your payment information. PCI DSS Level 1 certification.",
        keywords: ["stripe", "payments", "pci", "credit card", "secure"],
        isExternal: true,
    },
    {
        title: "Backtesting Guide",
        path: "https://docs.monkeys.finance/en/backtest",
        section: "Documentation",
        content: "Our backtesting feature lets you explore how our trading algorithms would have performed on real historical data.",
        keywords: ["backtest", "historical", "performance", "simulation", "testing", "guide"],
        isExternal: true,
    },
    {
        title: "Trade History",
        path: "https://docs.monkeys.finance/en/backtest#trade-history",
        section: "Documentation",
        content: "Detailed table of every trade during the backtest period. Position type, open and close dates, profit or loss, fees, equity.",
        keywords: ["trade", "history", "table", "profit", "loss", "fees"],
        isExternal: true,
    },
    {
        title: "Filtered Signals",
        path: "https://docs.monkeys.finance/en/backtest#filtered-signals",
        section: "Documentation",
        content: "Rows highlighted differently are filtered signals. ML evaluates each potential trade before execution.",
        keywords: ["filtered", "signals", "ml", "quality", "threshold"],
        isExternal: true,
    },
    {
        title: "Payments Guide",
        path: "https://docs.monkeys.finance/en/payments",
        section: "Documentation",
        content: "Learn about subscription plans, billing, and payment options in Monkeys Finance.",
        keywords: ["payments", "subscription", "billing", "pricing", "plans", "guide"],
        isExternal: true,
    },
    {
        title: "Subscription Plans",
        path: "https://docs.monkeys.finance/en/payments#subscription-plans",
        section: "Documentation",
        content: "Monthly plan billed every month, or annual plan billed once per year with 20% savings. Full access to all features.",
        keywords: ["subscription", "monthly", "annual", "yearly", "plans", "pricing"],
        isExternal: true,
    },
    {
        title: "Free Trial",
        path: "https://docs.monkeys.finance/en/payments#free-trial",
        section: "Documentation",
        content: "New users start with a free trial to explore all features. No payment information required to begin.",
        keywords: ["free", "trial", "no payment", "explore", "new users"],
        isExternal: true,
    },
    {
        title: "Machine Learning",
        path: "https://docs.monkeys.finance/en/ml",
        section: "Documentation",
        content: "Learn how our platform uses machine learning to enhance trading decisions and filter signals.",
        keywords: ["machine learning", "ml", "ai", "filter", "signals"],
        isExternal: true,
    },
    {
        title: "How ML Works",
        path: "https://docs.monkeys.finance/en/ml#how-ml-works",
        section: "Documentation",
        content: "ML analyzes trading signals before execution. Evaluates each potential trade based on historical patterns and market conditions.",
        keywords: ["ml", "analyze", "signals", "patterns", "market conditions"],
        isExternal: true,
    },
    {
        title: "Support",
        path: "https://docs.monkeys.finance/en/support",
        section: "Documentation",
        content: "If you have any questions, need assistance, or want to provide feedback, send us an email at monkeys.finance@gmail.com.",
        keywords: ["support", "help", "contact", "email", "questions", "feedback"],
        isExternal: true,
    },
];
