// Данные поиска для Fuse.js - Русский
// Объединяет страницы приложения и ссылки на документацию

import type { SearchItem } from "./searchData.en";

export const searchData: SearchItem[] = [
    // ===== СТРАНИЦЫ ПРИЛОЖЕНИЯ =====
    {
        title: "Алгоритмы",
        path: "/algorithms",
        content: "Просмотр активных торговых алгоритмов и их текущих сигналов. Мониторинг сигналов покупки и продажи для Bitcoin и Binance Coin.",
        keywords: ["алгоритмы", "сигналы", "торговля", "btc", "bnb", "покупка", "продажа"],
    },
    {
        title: "Экземпляры",
        path: "/instances",
        content: "Управляйте экземплярами автоматических торговых ботов. Создавайте, редактируйте, приостанавливайте или удаляйте торговых ботов.",
        keywords: ["экземпляры", "боты", "торговля", "автоматический", "управление"],
    },
    {
        title: "Уведомления",
        path: "/notifications",
        content: "Настройте уведомления о торговых сигналах через Telegram. Настройте оповещения для конкретных инструментов и стратегий.",
        keywords: ["уведомления", "оповещения", "telegram", "сигналы"],
    },
    {
        title: "Бэктест",
        path: "/backtest",
        content: "Изучите историческую эффективность торговых стратегий. Просмотр истории сделок с различными уровнями кредитного плеча.",
        keywords: ["бэктест", "история", "эффективность", "плечо", "тестирование"],
    },
    {
        title: "План",
        path: "/plan",
        content: "Управляйте планом подписки. Просмотр деталей выставления счетов и обновление подписки.",
        keywords: ["план", "подписка", "счета", "цены", "оплата"],
    },

    // ===== ДОКУМЕНТАЦИЯ (Внешние ссылки) =====
    {
        title: "Главная документации",
        path: "https://docs.monkeys.finance/ru",
        section: "Документация",
        content: "Добро пожаловать в документацию Monkeys Finance. Узнайте, как использовать нашу платформу алгоритмической торговли.",
        keywords: ["главная", "добро пожаловать", "документация", "docs", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "О нас",
        path: "https://docs.monkeys.finance/ru/about",
        section: "Документация",
        content: "О Monkeys Finance и нашей миссии предоставлять решения для алгоритмической торговли.",
        keywords: ["о нас", "миссия", "компания", "monkeys finance"],
        isExternal: true,
    },
    {
        title: "Руководство по экземплярам",
        path: "https://docs.monkeys.finance/ru/instances",
        section: "Документация",
        content: "Что такое экземпляр? Экземпляр — это конфигурация автоматического торгового бота, представляющая ваши личные торговые предпочтения.",
        keywords: ["экземпляр", "бот", "торговля", "автоматический", "конфигурация", "руководство"],
        isExternal: true,
    },
    {
        title: "Создание экземпляра",
        path: "https://docs.monkeys.finance/ru/instances#creating-instance",
        section: "Документация",
        content: "Чтобы создать новый экземпляр, откройте страницу Экземпляры в панели управления Monkeys Finance, нажмите Добавить экземпляр.",
        keywords: ["создать", "добавить", "новый", "экземпляр", "настройка"],
        isExternal: true,
    },
    {
        title: "Почему USDC?",
        path: "https://docs.monkeys.finance/ru/instances#why-usdc",
        section: "Документация",
        content: "Все торговые пары используют USDC в качестве базовой валюты вместо USDT. Это обеспечивает соответствие регуляциям MiCA ЕС.",
        keywords: ["usdc", "стейблкоин", "mica", "регуляция", "европа", "соответствие"],
        isExternal: true,
    },
    {
        title: "Режим Testnet",
        path: "https://docs.monkeys.finance/ru/instances#testnet-mode",
        section: "Документация",
        content: "Режим testnet позволяет тестировать торговые стратегии с демо-средствами перед риском реальных денег.",
        keywords: ["testnet", "демо", "тест", "бумажная торговля", "симуляция"],
        isExternal: true,
    },
    {
        title: "Руководство по уведомлениям",
        path: "https://docs.monkeys.finance/ru/notifications",
        section: "Документация",
        content: "Уведомления информируют вас о торговых сигналах в реальном времени. Настройте, какие сигналы вы хотите получать.",
        keywords: ["уведомления", "оповещения", "сигналы", "telegram", "реальное время", "руководство"],
        isExternal: true,
    },
    {
        title: "Настройка Telegram",
        path: "https://docs.monkeys.finance/ru/notifications#telegram",
        section: "Документация",
        content: "Получайте мгновенные уведомления о торговых сигналах через Telegram. Найдите @algo_squid_bot и отправьте команду /start.",
        keywords: ["telegram", "бот", "настройка", "мессенджер", "чат"],
        isExternal: true,
    },
    {
        title: "Алгоритмы и инструменты",
        path: "https://docs.monkeys.finance/ru/instruments",
        section: "Документация",
        content: "Узнайте о наших алгоритмах и почему мы фокусируемся на Bitcoin и Binance Coin для наших торговых стратегий.",
        keywords: ["алгоритмы", "инструменты", "btc", "bnb", "bitcoin", "binance coin", "руководство"],
        isExternal: true,
    },
    {
        title: "Bitcoin (BTC)",
        path: "https://docs.monkeys.finance/ru/instruments#bitcoin",
        section: "Документация",
        content: "Bitcoin остается бесспорным лидером крипторынка, занимая около 60% общей рыночной капитализации.",
        keywords: ["bitcoin", "btc", "крипто", "доминирование", "цифровое золото"],
        isExternal: true,
    },
    {
        title: "Binance Coin (BNB)",
        path: "https://docs.monkeys.finance/ru/instruments#binance-coin",
        section: "Документация",
        content: "BNB функционирует как акция в экосистеме Binance. Скидки на торговые комиссии, награды за стейкинг.",
        keywords: ["bnb", "binance", "coin", "утилита", "биржа", "стейкинг"],
        isExternal: true,
    },
    {
        title: "Безопасность",
        path: "https://docs.monkeys.finance/ru/safety",
        section: "Документация",
        content: "Узнайте, как мы защищаем ваши данные и обеспечиваем безопасность. Архитектура глубокой защиты.",
        keywords: ["безопасность", "защита", "данные", "шифрование"],
        isExternal: true,
    },
    {
        title: "Шифрование API-ключей",
        path: "https://docs.monkeys.finance/ru/safety#api-encryption",
        section: "Документация",
        content: "Многоуровневое шифрование для API-ключей. Шифрование на стороне клиента, AES-256-GCM, уникальные ключи для каждого пользователя.",
        keywords: ["api", "ключи", "шифрование", "aes", "безопасный", "учетные данные"],
        isExternal: true,
    },
    {
        title: "Руководство по бэктестингу",
        path: "https://docs.monkeys.finance/ru/backtest",
        section: "Документация",
        content: "Функция бэктестинга позволяет изучить, как наши алгоритмы работали бы на реальных исторических данных.",
        keywords: ["бэктест", "исторический", "эффективность", "симуляция", "тестирование", "руководство"],
        isExternal: true,
    },
    {
        title: "История сделок",
        path: "https://docs.monkeys.finance/ru/backtest#trade-history",
        section: "Документация",
        content: "Детальная таблица каждой сделки за период бэктеста. Тип позиции, даты открытия и закрытия, прибыль или убыток.",
        keywords: ["сделка", "история", "таблица", "прибыль", "убыток", "комиссии"],
        isExternal: true,
    },
    {
        title: "Руководство по оплате",
        path: "https://docs.monkeys.finance/ru/payments",
        section: "Документация",
        content: "Узнайте о планах подписки, выставлении счетов и вариантах оплаты в Monkeys Finance.",
        keywords: ["оплата", "подписка", "счета", "цены", "планы", "руководство"],
        isExternal: true,
    },
    {
        title: "Планы подписки",
        path: "https://docs.monkeys.finance/ru/payments#subscription-plans",
        section: "Документация",
        content: "Месячный план с ежемесячной оплатой или годовой план с оплатой раз в год с экономией 20%. Полный доступ ко всем функциям.",
        keywords: ["подписка", "месячный", "годовой", "планы", "цены"],
        isExternal: true,
    },
    {
        title: "Бесплатный пробный период",
        path: "https://docs.monkeys.finance/ru/payments#free-trial",
        section: "Документация",
        content: "Новые пользователи начинают с бесплатного пробного периода для изучения всех функций. Платежная информация не требуется.",
        keywords: ["бесплатно", "пробный", "без оплаты", "изучить", "новые пользователи"],
        isExternal: true,
    },
    {
        title: "Машинное обучение",
        path: "https://docs.monkeys.finance/ru/ml",
        section: "Документация",
        content: "Узнайте, как наша платформа использует машинное обучение для улучшения торговых решений и фильтрации сигналов.",
        keywords: ["машинное обучение", "ml", "ии", "фильтр", "сигналы"],
        isExternal: true,
    },
    {
        title: "Поддержка",
        path: "https://docs.monkeys.finance/ru/support",
        section: "Документация",
        content: "Если у вас есть вопросы, нужна помощь или хотите оставить отзыв, напишите нам на monkeys.finance.ca@gmail.com.",
        keywords: ["поддержка", "помощь", "контакт", "email", "вопросы", "отзыв"],
        isExternal: true,
    },
];
